image:
  repository: kanika3000/nginx-helm
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 3005

replicaCount: 3

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

