name: Deploy to Kubernetes using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v3.14.4'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v1.28.0'

    - name: Create kubeconfig file
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > ${{ github.workspace }}/kubeconfig

    - name: Deploy to Kubernetes using Helm
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
      run: |
        cd nginxapp
        helm upgrade --install my-app . \
        --set image.repository=kanika3000/nginx-helm \
        --set image.tag=latest \
        --namespace default

